name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
# on:
#   workflow_dispatch: # Manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and tag Docker image
        run: |
          docker buildx build --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/swiftbidbackend:${{ github.sha }} --tag ${{ secrets.DOCKERHUB_USERNAME }}/swiftbidbackend:latest --push .
